exported/linux/zzub:
	mkdir -p exported/linux/
	godot-4 --export linux exported/linux/zzub

exported/windows/zzub.exe:
	mkdir -p exported/windows/
	godot-4 --export windows exported/windows/zzub.exe

exported/macos/zzub:
	mkdir -p exported/macos/
	godot-4 --export macos exported/macos/zzub
